export const IPC = {
  getConfig: "app:get-config",
  getPermissionStatus: "perm:status",
  startCalibration: "perm:calibrate",
  prepareCalibration: "perm:prepare-calibration",
  calibrationFailed: "perm:calibration-failed",
  enterDemoMode: "app:demo-mode",
  quitApp: "app:quit",
  summon: "session:summon",
  selectOption: "session:select-option",
  more: "session:more",
  back: "session:back",
  beginHint: "session:begin-hint",
  updateHint: "session:update-hint",
  clearHint: "session:clear-hint",
  acceptHintCandidate: "session:accept-hint-candidate",
  commitHintLiteral: "session:commit-hint-literal",
  requestCompletion: "session:request-completion",
  exitSession: "session:exit",
  confirmYes: "confirm:yes",
  confirmChange: "confirm:change",
  confirmRead: "confirm:read",
  confirmCancel: "confirm:cancel",
  interruptExecutor: "executor:interrupt",
  steer: "executor:steer",
  consequentialChoice: "executor:consequential-choice",
  recovery: "recovery:choose",
  gazeAnchor: "gaze:anchor",
  gazeSampleTelemetry: "gaze:sample-tel",
  navigationScroll: "navigation:scroll",
  getDebugInfo: "debug:get",
  toggleHud: "debug:toggle-hud",
  forceState: "debug:force-state",
  simulateAction: "debug:simulate",
  getTelemetry: "tel:get-summary",
  notice: "app:notice",
  viewUpdate: "view:update",
  speechUpdate: "view:speech",
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
