export const IPC = {
  getConfig: "app:get-config",
  getPermissionStatus: "perm:status",
  startCalibration: "perm:calibrate",
  prepareCalibration: "perm:prepare-calibration",
  calibrationFailed: "perm:calibration-failed",
  enterDemoMode: "app:demo-mode",
  quitApp: "app:quit",
  summon: "session:summon",
  prefetchOption: "session:prefetch-option",
  selectOption: "session:select-option",
  more: "session:more",
  back: "session:back",
  exitSession: "session:exit",
  interruptExecutor: "executor:interrupt",
  steer: "executor:steer",
  consequentialChoice: "executor:consequential-choice",
  recovery: "recovery:choose",
  contextToggle: "context:toggle",
  contextApproveSession: "context:approve-session",
  gazeAnchor: "gaze:anchor",
  gazeSample: "gaze:sample",
  notchVisual: "notch:visual",
  navigationScroll: "navigation:scroll",
  getDebugInfo: "debug:get",
  toggleHud: "debug:toggle-hud",
  forceState: "debug:force-state",
  simulateAction: "debug:simulate",
  notice: "app:notice",
  viewUpdate: "view:update",
  speechUpdate: "view:speech",
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
